# Generated by Django 4.0.1 on 2022-04-07 07:58

from django.db import migrations, models
import tattoo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True, verbose_name='firstname')),
                ('lastname', models.CharField(blank=True, max_length=255, null=True, verbose_name='lastname')),
                ('account_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='account_type')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='password')),
                ('image', models.ImageField(default='uploads/Cases.png', upload_to=tattoo.models.nameFile, verbose_name='image')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
