# Generated by Django 4.0.1 on 2022-04-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tattoo',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='tattoo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tattoo',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='tattoo',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='tattoo',
            name='password',
        ),
        migrations.AddField(
            model_name='tattoo',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='tattoo_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tattoo_name'),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id'),
        ),
    ]
