# Generated by Django 4.0.1 on 2022-05-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0002_remove_tattoo_account_type_remove_tattoo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoo',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='status'),
        ),
    ]
