# Generated by Django 4.0.1 on 2022-05-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0003_tattoo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoo',
            name='time_estimation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='time_estimation'),
        ),
    ]
