# Generated by Django 4.0.1 on 2022-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='status'),
        ),
    ]
