# Generated by Django 4.0.1 on 2022-05-22 14:01

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='uploads/Cases.png', upload_to=category.models.nameFile, verbose_name='image'),
        ),
    ]
