# Generated by Django 4.0.1 on 2022-04-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='user_id')),
                ('artist_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='artist_id')),
                ('design_id', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='design_id')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='status')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
